### ISSUE TITLE
Possible to display mean instead of median?

### ISSUE THREAD

**Issue by SiljeHS** [njudd/ggrain#3]
Hi! 

Thank you for creating this package, which enables an r noob like myself to create beautiful raincloud plots!

I'm using the ggrain package to make raincloud plots to display change across repeated measures, and we are planning to use the plots for an upcoming paper. After comparing the output plots to our data and descriptive stats, it seems to me that the raincloud plots display median values instead of mean. Is this correct? Our statistical approach compares means - as such, is there a way to display the mean values in the plots instead of the median? 
Best, Silje

**Comment by njudd** [comment]
Dear Silje,

As a matter of convention, it is important that box plots always show the median. 

Yet, you could get rid of the boxplots and add the mean with stat_summary(). Here is an example that will work if you run the [full vingette](https://github.com/njudd/ggrain/blob/main/vignettes/ggrain.Rmd).

`ggplot(iris.long[iris.long$time %in% c('t1', 't2'),], aes(time, Sepal.Width, fill = Species)) +
    geom_rain(alpha = .5, rain.side = 'f2x2', boxplot.args = list(color = NA, fill = NA)) +
    theme_classic() +
    stat_summary(fun = mean, geom = "line", aes(group = Species, color = Species), position = position_nudge(x = c(-.1, .1, -.1, .1))) +
    stat_summary(fun = mean, geom = "point",
                 aes(group = Species, color = Species), position = position_nudge(x = c(-.1, .1, -.1, .1))) +
    scale_fill_manual(values=c("dodgerblue", "darkorange")) +
    scale_color_manual(values=c("dodgerblue", "darkorange")) +
    guides(fill = 'none', color = 'none')`
    
![Screen Shot 2023-02-15 at 5 14 24 PM](https://user-images.githubusercontent.com/24483076/219086077-c1748884-071e-428c-b70c-3aa0d2af24e6.png)

Please cite the package if you use it for a paper, thanks :)

**Comment by njudd** [comment]
We will have a workshop on Friday!
Sign up here: https://github.com/jorvlan/raincloudplots-workshops

**Comment by SiljeHS** [comment]
Thank you so much for this quick and informative reply, and for your time. This is incredibly helpful! And of course, the box plot. Basic knowledge. I’ve seemed to lost track of this during my steep R learning curve the past few weeks. The workshop you linked to looks very helpful, and I’ll keep an eye out for the next one.Yes, we will cite the package. Awesome work! Thanks for providing the code for this, and making it accessible! Best, Silje15. feb. 2023 kl. 17:15 skrev njudd ***@***.***>:﻿
Dear Silje,
As a matter of convention, it is important that box plots always show the median.
Yet, you could get rid of the boxplots and add the mean with stat_summary(). Here is an example that will work if you run the full vingette.
ggplot(iris.long[iris.long$time %in% c('t1', 't2'),], aes(time, Sepal.Width, fill = Species)) + geom_rain(alpha = .5, rain.side = 'f2x2', boxplot.args = list(color = NA, fill = NA)) + theme_classic() + stat_summary(fun = mean, geom = "line", aes(group = Species, color = Species), position = position_nudge(x = c(-.1, .1, -.1, .1))) + stat_summary(fun = mean, geom = "point", aes(group = Species, color = Species), position = position_nudge(x = c(-.1, .1, -.1, .1))) + scale_fill_manual(values=c("dodgerblue", "darkorange")) + scale_color_manual(values=c("dodgerblue", "darkorange")) + guides(fill = 'none', color = 'none')

Please cite the package if you use it for a paper, thanks :)
