### ISSUE TITLE
Error generating geom_rain: 'gpar' element 'lwd' must not be length 0

### ISSUE THREAD

**Issue by matthew-robison** [njudd/ggrain#4]
I am trying to generate a raincloud plot, but I am encountering the following error:

Error in check.length(gparname) : 
  'gpar' element 'lwd' must not be length 0

I tried first with my own data, but this error happens even if I run the following:

ggplot(iris, aes(Species, Sepal.Width, fill = Species)) +
  geom_rain(alpha = .5)

I had first tried to use the ggrain package and was being told my version of vctrs was outdated (0.4.1), so I updated to 0.5.2.

I appreciate any help.

**Comment by njudd** [comment]
Can you check your ggplot version and update to 3.4.1? It could be that

**Comment by matthew-robison** [comment]
that worked! Sorry I didn't think of that sooner.

**Comment by njudd** [comment]
Re-opening this issue until ggrain v 0.0.3 comes out with the requirement for `ggplot2 =>3.4.0`.

I will wait a month in case new bugs or features come up.

**Comment by njudd** [comment]
v0.0.3 out
